name: "tts"
backend: "python"

max_batch_size: 0

input [
  {
    name: "TEXTS"
    data_type: TYPE_STRING
    dims: [ -1 ]   # list of text chunks
  },
  {
    name: "VOICE_PROMPT_PCM"
    data_type: TYPE_FP32
    dims: [ -1 ]
    optional: true
  },
  {
    name: "VOICE_PROMPT_SAMPLE_RATE"
    data_type: TYPE_INT32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "VOICE_ID"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  },
  {
    name: "BACKBONE_TEMPERATURE"
    data_type: TYPE_FP32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "BACKBONE_TOP_P"
    data_type: TYPE_FP32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "DEPTH_TEMPERATURE"
    data_type: TYPE_FP32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "DEPTH_TOP_P"
    data_type: TYPE_FP32
    dims: [ 1 ]
    optional: true
  },
  {
    name: "START"
    data_type: TYPE_BOOL
    dims: [1]
    optional: true
  },
  {
    name: "END"
    data_type: TYPE_BOOL
    dims: [1]
    optional: true
  },
  {
    name: "CORRID"
    data_type: TYPE_INT64
    dims: [1]
  },
  {
    name: "TARGET_SAMPLE_RATE"
    data_type: TYPE_INT32
    dims: [1]
    optional: true
  }
]

output [
  {
    name: "AUDIO_FRAME"
    data_type: TYPE_FP32
    dims: [ -1 ]     # streamed chunk
  }
]

sequence_batching {
  max_sequence_idle_microseconds: 120000000  # 120 seconds

  control_input [
    {
      name: "START"
      control [
        {
          kind: CONTROL_SEQUENCE_START
          bool_false_true: [ false, true ]
        }
      ]
    },
    {
      name: "END"
      control [
        {
          kind: CONTROL_SEQUENCE_END
          bool_false_true: [ false, true ]
        }
      ]
    }
  ]
}


model_transaction_policy {
  decoupled: true
}

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]

parameters: {
  key: "default_voice_id"
  value: { string_value: "alba" }
}
